name: 'Build & test frontend reusable action'
description: 'Build & test frontend reusable action'
author: 'Gutenberg Technology'


inputs:
  artifact-name:
    description: 'Artifact name'
    required: false
    default: ''
  install-cmd:
    description: 'Command for installing dependencies'
    required: true
  build-cmd:
    description: 'Command for building'
    required: true
  lint-cmd:
    description: 'Command for linting'
    required: false
    default: ''
  test-cmd:
    description: 'Command for running testing'
    required: false
    default: ''
  dist_path:
    description: 'Path to the dist folder'
    required: true
    default: 'dist'
runs:
  using: 'composite'
  steps:
    - name: 'Read .nvmrc'
      id: read-nvmrc
      run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.read-nvmrc.outputs.node-version }}

    - name: 'Install'
      run: ${{ inputs.install-cmd }}
      shell: bash

    - name: 'Lint'
      if: inputs.lint-cmd != ''
      run: ${{ inputs.lint-cmd }}
      shell: bash

    - name: 'Build'
      run: ${{ inputs.build-cmd }}
      shell: bash

    - name: 'Test'
      if: inputs.test-cmd != ''
      run: ${{ inputs.test-cmd }}
      shell: bash

    - name: 'Upload Archive'
      uses: 'actions/upload-artifact@v4'
      if: inputs.artifact-name != ''
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.dist_path }}
        if-no-files-found: error
